# https://fixmypc.ru/post/sozdanie-i-zapusk-konteinera-docker-s-django-postgressql-gunicorn-i-nginx/

version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./mysite
    # Запускаем сервер gunicorn - вместо python manage.py runserver 0.0.0.0:8000
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - db

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_volume: